[package]
name = "arbor_ui"
version = "0.1.0"
authors = ["David Schwarz <dsdavidschwarz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
futures-lite = "1.11"
egui = "0.10"
epi = "0.10.0"
egui_wgpu_backend = "0.5"
egui_winit_platform = "0.5"
wgpu = "0.7"
winit = "0.24"
bytemuck = { version = "1.4.1", features = ["derive"]}
rayon = "1.5"
cgmath = "0.18.0"
log = "0.4.11"
futures = "0.3.6"
